# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
    famility_takeme_backoffice-postgresql:
        image: postgres:11
        # volumes:
        #     - ~/volumes/jhipster/famility_backoffice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=famility_takeme_backoffice
            - POSTGRES_USER=famility_takeme
            - POSTGRES_PASSWORD=famility_takeme
            - POSTGRES_HOST_AUTH_METHOD=trust
        # If you want to expose these ports outside your dev PC,
        # remove the "127.0.0.1:" prefix
        ports:
            - 127.0.0.1:5432:5432
